include/geometrycentral/ply_wrapper.h

This PR upgrades happly's version of geometry-central to the current master (with a quick fix on the ply_wrapper).
The previous version happly generates build issues (virtual destructor one) that have been fixed in the master (which also makes polyscope impossible to build on mac with the latest clang).

Happly upgrade +  fix

---

include/geometrycentral/numerical/linear_solvers.h
include/geometrycentral/surface/halfedge_containers.h
src/numerical/eigenproblem_solvers.cpp

The current k-eigenvalue solver does not work on complex matrices. For complex vectors, `x.transpose() * v` does not give the dot product. I switched to Eigen's `dot` function, which should work in both the real and complex case. Also for projections onto complex vectors, you need to write the dot product in a particular order - `v.dot(x) != x.dot(v)`. So I switched the order of `v` and `x` in the projection.

Updated eigenvalue solver for complex matrices

---

include/geometrycentral/surface/base_geometry_interface.h
include/geometrycentral/surface/edge_length_geometry.h
src/surface/edge_length_geometry.cpp
src/surface/heat_method_distance.cpp
src/surface/vertex_position_geometry.cpp
test/src/halfedge_geometry_test.cpp

Change the heat method for distance to use a lumped mass matrix; it works better.
Fix #15 by deleting not-actually-supported implicit copy of geometry objects. Also add copy tests, and implement missing copy for EdgeLengthGeometry.

Bugfixes to heat distance and geometry copy

---

include/geometrycentral/surface/polygon_soup_mesh.h
include/geometrycentral/utilities/vector2.h
include/geometrycentral/utilities/vector2.ipp
include/geometrycentral/utilities/vector3.h
include/geometrycentral/utilities/vector3.ipp
src/surface/meshio.cpp
src/surface/polygon_soup_mesh.cpp

I added parsers for ASCII and binary STL files. I also added a function to merge vertices with the same positions, which lets you build halfedge meshes out of the STL models.
`mergeIdenticalVertices()` assumes that the vertices have exactly the same coordinates in floating point - I tried a version that merged vertices up to a small tolerance, but that was significantly slower, and this seems to work fine on the few Thingi10k models that I tried.

Added STL parser

---

cmake/EigenChecker.cmake
cmake/FindEigen3.cmake

Under certain awful system configuration conditions... it's apparently possible for `find_path()` to set a bogus Eigen location in `EIGEN3_INCLUDE_DIR`. Subsequent calls to `find_path()` will default to the previously found location even though its wrong (c.f. https://cmake.org/cmake/help/latest/command/find_path.html second to last paragraph).
Also `find_path(<var> ...)` expects a value of the form `<var>-NOTFOUND` or if the variable is uninitialized. The empty string value, for example, appears to also satisfy the cached value check.
This PR explicitly sets `EIGEN3_INCLUDE_DIR` to value `EIGEN3_INCLUDE_DIR-NOTFOUND` to avoid using an incorrect cached path in the future.

Unset EIGEN3_INCLUDE_DIR on failure

---

src/surface/rich_surface_mesh_data.cpp

I had a compile error with GCC8.2 with -Werror and the exceptions ([https://www.nsnam.org/bugzilla/show_bug.cgi?id=2917](https://www.nsnam.org/bugzilla/show_bug.cgi?id=2917))

bugfix GCC8.2 -Werror=catch-value=

---

src/surface/manifold_surface_mesh.cpp

Currently it returns the old face n times.
The halfedge returned by `connectVertices` is the halfedge in the old face that is adjacent to the new face. So `connectHe.twin().face()` is guaranteed to be in the newly-created face.

Fix triangulate to return list of new faces

---

docs/docs/surface/utilities/io.md
include/geometrycentral/surface/meshio.h
include/geometrycentral/surface/surface_mesh_factories.h
src/surface/halfedge_factories.cpp
src/surface/meshio.cpp
src/surface/surface_mesh_factories.cpp

This PR adds a new method `readParameterizedManifoldSurfaceMesh()` that loads an OBJ file with UV coordinates directly into a `ManifoldSurfaceMesh` and associated `CornerData`.  It does not break compatibility with any existing methods for reading data; just adds one that loads UVs.
To implement it, I generalized the method `makeManifoldSurfaceMeshAndGeometry` to take a list of UV coordinates (with the same format produced by `SimplePolygonMesh`).  This method is the "general purpose" method, and returns a list that always includes UVs.  Other wrapper methods take a subset of the return values and return them.
Note that, internally, the mechanism for returning a subset of the return values is a bit ugly, and follows this pattern:
```
auto lvals = …
```

Add method for loading UVs with ManifoldSurfaceMesh

---

src/surface/intrinsic_triangulation.cpp

Looks like we missed this when implementing the general intrinsic triangulation class. I just copied the function from the old signpost code

Implement `setMarkedEdges`

---

include/geometrycentral/surface/mutation_manager.h
include/geometrycentral/surface/quadric_error_simplification.h
include/geometrycentral/surface/subdivide.h
src/CMakeLists.txt
src/surface/manifold_surface_mesh.cpp
src/surface/mutation_manager.cpp
src/surface/quadric_error_simplification.cpp
src/surface/subdivide.cpp

I added implementations of quadric error simplification, Catmull-Clark subdivision, and Loop subdivision. Quadric error simplification and Loop subdivision optionally take a `MutationManager` argument. Unfortunately, Catmull-Clark doesn't, since `MutationManager` is tailored for triangle meshes at the moment.
I also changed `MutationManager`'s mutations to return the newly-created mesh element (i.e. `mutationManager.collapseEdge(e)` now returns the new vertex).

Simplification & subdivision

---

docs/docs/surface/algorithms/geodesic_distance.md
include/geometrycentral/surface/exact_geodesic_helpers.h
include/geometrycentral/surface/exact_geodesic_helpers.ipp
include/geometrycentral/surface/exact_geodesics.h
src/CMakeLists.txt
src/surface/exact_geodesic_helpers.cpp
src/surface/exact_geodesics.cpp

I ported Kirsanov's implementation of MMP to run in geometry central on intrinsic triangulations. Now it uses geometry central's mesh data structures and does its computations based on edge lengths rather than vertex positions, but all of the algorithm logic (and most of the code) is left exactly the same.
After doing this, I noticed that there is a bunch of commented-out code in `exact_polyhedral_geodesics.h` 😄. What's the status of that stuff? If there are plans for getting it working soon, I'd be happy to make any changes to this code to give a more consistent interface or otherwise delineate the differences more clearly.
Also, I'm not totally sure how licensing is supposed to work here. Kirsanov's code is MIT licensed, so based on a cursory google search it seems like it's legal to …

Intrinsic MMP

---

include/geometrycentral/surface/integer_coordinates_intrinsic_triangulation.h
include/geometrycentral/surface/intrinsic_triangulation.h
include/geometrycentral/surface/normal_coordinates.h
include/geometrycentral/surface/signpost_intrinsic_triangulation.h
include/geometrycentral/surface/surface_point.h
include/geometrycentral/surface/surface_point.ipp
src/surface/integer_coordinates_intrinsic_triangulation.cpp
src/surface/intrinsic_triangulation.cpp
src/surface/normal_coordinates.cpp
src/surface/signpost_intrinsic_triangulation.cpp

Here are a few bug fixes/quality of life improvements for integer coordinates intrinsic triangulations.
1. Now the integer coordinate `splitEdge` function takes a halfedge rather than an edge, and returns the halfedge incident on the inserted vertex which points in the same direction. (I think this was always the desired behavior for `IntrinsicTriangulation`s, but integer coordinates didn't quite keep track of all the orientations properly 😛)
2. I moved `recoverTraceTValues` (the function for computing barycentric coordinates along a traced edge) into `IntrinsicTriangulation` rather than keeping it as a member of `SignpostIntrinsicTriangulation` in particular. I also fixed an off-by-one error which made all the barycentric coordinates wrong.
3. I added some code to explicitly update …

Improvements to integer coordinate edge splits

---

CMakeLists.txt
src/CMakeLists.txt

Thie PR adds the following
- install target installs the library and header files to `CMAKE_INSTALL_PREFIX`
- if user requests `BUILD_SHARED_LIBS` for a `MSVC` build symbols are automatically exported

Cmake fixes

---

include/geometrycentral/surface/exact_geodesics.h
include/geometrycentral/surface/halfedge_element_types.ipp
include/geometrycentral/surface/surface_mesh.h
src/surface/exact_geodesics.cpp
src/surface/surface_mesh.cpp

This should fix issue #119 about running MMP on meshes with boundary. 
There was a bug in the MMP implementation (a line I accidentally deleted while porting the code over) which only caused problems on `ManifoldSurfaceMesh`es with boundary, as well as a bug in the `Vertex::isBoundary()` check on nonmanifold meshes.

Nonmanifold mmp

---

docs/docs/surface/geometry/quantities.md
include/geometrycentral/surface/intrinsic_geometry_interface.h
include/geometrycentral/surface/mutation_manager.ipp
src/surface/intrinsic_geometry_interface.cpp

I've added three functions in `intrinsic_geometry_interface.cpp`, implementing a `crouzeixRaviartLaplacian`, `crouzeixRaviartMassMatrix`, and `crouzeixRaviartConnectionLaplacian`. These operators/matrix are analogous to the vertex-based cotan Laplacian and Galerkin mass matrix, but discretized using the _Crouzeix-Raviart_ (C-R) basis functions instead. The C-R basis elements are essentially Lagrange elements but based at edge midpoints: They are piecewise linear, have a value at 1 at its associated edge midpoint, and is 0 at all other adjacent edge midpoints.
In graphics/geometry processing, C-R elements have been used, for example, to [discretize bending energies](https://cims.nyu.edu/gcl/papers/wardetzky2007dqb.pdf), do [Hodge decomposition](http://www.polthier.info/articles/hodge/hodge_ …

Crouzeix raviart Laplacians and mass matrix

---

src/numerical/qr_solvers.cpp

Currently, solving underdetermined systems using SuiteSparse by calling `solve` does not work. For example,
```
#include "geometrycentral/numerical/linear_solvers.h"
Eigen::Matrix<double, 2, 3> A;
A << 1, 0, 1, 0, 1, 0 ;
Vector<double> b(2);
b << 1, 2;
SparseMatrix<double> sparseA = A.sparseView();
Vector<double> sol = solve(sparseA, b);
std::cout << sol << std::endl;
```
will print out `1 1 1`, but the correct answer is `0.5 2 0.5`. This is because SuiteSparse's QR decomposition includes a permutation matrix (i.e., `E` such that `QR=AE`), but geometry central does not properly account for this in the call to `SuiteSparseQR_solve`. (Thank you @MarkGillespie for helping to find the bug!)

Fix SuiteSparse call for underdetermined systems

---

docs/docs/surface/utilities/barycentric_vector.md
include/geometrycentral/surface/barycentric_vector.h
include/geometrycentral/surface/barycentric_vector.ipp
src/CMakeLists.txt
src/surface/barycentric_vector.cpp

Nothing major -- just added additional functionality to the `BarycentricVector` object:
- `rotated90()` now supports edge-type vectors as input
- a new function `rotated()` allows rotation of vectors by arbitrary angles
- added some more detailed comments in the code so I don't forget how I derived quantities :)
- documentation updated accordingly.
Let me know if you need me to add additional test functions to geometry-central -- for these few commits, I tested everything using an external program: https://github.com/nzfeng/barycentric-vector-demo

Updating the functionality of barycentric vectors

---

docs/docs/surface/algorithms/surface_sampling.md
include/geometrycentral/surface/poisson_disk_sampler.h
src/surface/poisson_disk_sampler.cpp
test/CMakeLists.txt
test/src/poisson_disk_sampler_test.cpp

Fixed #184 
Sampling only behaved reasonable when the mean edge length was close to 1, because the "rMinDist" was treated as if it where the squared min. distance (sqrt was taken).
This PR fixes this issue and adds a test.
- a 1x1 square disk is sampled with distance=0.1
- a 100x100 square disk is sampled with distance=10 (i.e., 100*0.1)
In both cases we expect a similar number of points (seed cannot be set from API).
Without the fix, I get approx. 650 (width=1) vs 10 (width=100) points.

fix bug in PoissonDiskSampler, add test

---

include/geometrycentral/utilities/element_iterators.h
include/geometrycentral/utilities/element_iterators.ipp
include/geometrycentral/utilities/mesh_data.h

Hello,
As a mesh is a graph with vertices and edges it is sometimes useful to run graph algorithms on a mesh.
This PR is the first step towards this goal which will enable to write code like
```cpp
geometrycentral::surface::VertexData<double> distance(*mesh);
auto source = *(vertices(*mesh).first);
boost::breadth_first_search(*mesh, source,
boost::visitor(boost::make_bfs_visitor(boost::record_distances(boost::make_assoc_property_map(distance), boost::on_tree_edge())))
.vertex_index_map(boost::associative_property_map<geometrycentral::surface::VertexData<std::size_t>>(mesh->getVertexIndices())));
for(auto v : mesh->vertices()){
std::cout << v << " at distance " << distance[v] << std::endl;
}
```

Working towards running BGL algorithms on ManifoldSurfaceMesh

---

deps/CMakeLists.txt

Currently, `deps/CMakeLists.txt` requires CMAKE version 3.30 due to the line `cmake_policy(SET CMP0169 OLD)`. This policy fixes a deprecation added in 3.30, so it is only needed in versions greater than or equal to 3.30. The fix here causes the cmake_policy command to only be called in this case, thus restoring functionality in previous cmake versions. 
This builds on my machine with cmake version 3.31.2.

fix cmake version issue

---

docs/docs/surface/geometry/quantities.md

Hopefully the title is self-explanatory, there was a sign typo on the formula for computing the integrated Gaussian curvature on a face using the angle defect. The actual code doesn't have this typo, so this pull request only affects the docs.

Fix sign typo on "face Gaussian curvature" doc
